#!/bin/bash
if [ -z "$FNKR_C9_AUTOEXEC" ]; then
    # fnkr/c9-scripts
    export FNKR_C9_NAME="fnkr/c9-scripts"
    export FNKR_C9_LIBRARY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    export PATH="$PATH:$FNKR_C9_LIBRARY/utils"

    # Google AppEngine/Go
    if [ -d "$HOME/appengine_go" ]; then
        export PATH="$PATH:$HOME/appengine_go"
        export PATH="$PATH:$FNKR_C9_LIBRARY/appengine_go"
    fi

    # fnkr/c9-scripts
    export FNKR_C9_AUTOEXEC="true"
fi
