#!/bin/bash
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/autoexec" || exit 1

PORT="$(find-free-port)" || exit 1
echo "$FNKR_C9_NAME: godoc-http: info: godoc serves on https://$C9_HOSTNAME:$PORT"
godoc -http="$IP:$PORT" -play "$@"
