#!/bin/bash
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/autoexec" || exit 1

if [ -e "$HOME/appengine_python_php" ]; then
    echo "$FNKR_C9_NAME: install_appengine_python_php: error: already installed. remove ~/appengine_python_php to reinstall."
    exit 1
fi

SDK_URL='https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.37.zip'

if ! SDK_ZIP="/tmp/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 8)"; then
    echo "$FNKR_C9_NAME: install_appengine_python_php: error: could not generate random string."
    exit 1
fi

if ! SDK_UNP="/tmp/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 8)"; then
    echo "$FNKR_C9_NAME: install_appengine_python_php: error: could not generate random string."
    exit 1
fi

if ! wget -O "$SDK_ZIP" "$SDK_URL"; then
    echo "$FNKR_C9_NAME: install_appengine_python_php: error: could not download sdk. invalid url?"
    exit 1
fi

if ! mkdir "$SDK_UNP"; then
    echo "$FNKR_C9_NAME: install_appengine_python_php: error: could not create temporary directory."
    exit 1
fi

if ! unzip "$SDK_ZIP" -d "$SDK_UNP"; then
    echo "$FNKR_C9_NAME: install_appengine_python_php: error: could not extract sdk."
    exit 1
fi

if ! mv "$SDK_UNP/google_appengine" "$HOME/appengine_python_php"; then
    echo "$FNKR_C9_NAME: install_appengine_python_php: error: could not move $SDK_UNP/google_appengine to ~/appengine_python_php."
    exit 1
fi

if ! rm "$SDK_ZIP"; then
    echo "$FNKR_C9_NAME: install_appengine_python_php: error: could not remove appengine sdk zip ($SDK_ZIP)."
    exit 1
fi

if ! rm -rf "$SDK_UNP"; then
    echo "$FNKR_C9_NAME: install_appengine_go: error: could not remove appengine sdk tmp dir ($SDK_UNP)."
    exit 1
fi
