#!/bin/bash
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/autoexec" || exit 1

sudo apt-get install gcc python-dev python-setuptools libffi-dev && \
sudo apt-get install python-pip && \
sudo pip install -U gsutil
