#!/bin/bash
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/autoexec" || exit 1

# run as root
if [ "$UID" != "0" ]; then
    sudo -E "$0" "$@"
    exit
fi

# stop apache2
service apache2 stop || exit 1

# find free port
PORT="$(find-free-port)" || exit 1

# update apache2 config
find-free-port -a | while read port; do sed "s/$port/$PORT/" -i /etc/apache2/ports.conf; done || exit 1
find-free-port -a | while read port; do sed "s/$port/$PORT/" -i /etc/apache2/sites-available/001-cloud9.conf; done || exit 1

# get adminer
wget 'https://www.adminer.org/latest.php' -O /usr/share/phpmyadmin/adminer.php || exit 1

# start apache2
service apache2 start

# return adminer url
echo "Adminer has been installed to https://$C9_HOSTNAME:$PORT/phpmyadmin/adminer.php"
