#!/bin/bash
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/autoexec" || exit 1

# run as root
if [ "$UID" != "0" ]; then
    sudo -E "$0" "$@"
    exit
fi

# add repository
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash || exit 1

# install git-lfs
apt-get -y install git-lfs || exit 1

# add git-lfs filters to git
git lfs install || exit 1
