#!/bin/bash
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/autoexec" || exit 1

# run as root
if [ "$UID" != "0" ]; then
    sudo -E "$0" "$@"
    exit
fi

apt-get install -y mongodb-org || exit 1
