#!/bin/bash
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/autoexec" || exit 1

sudo sed 's/8080/8081/' -i /etc/apache2/ports.conf && \
sudo sed 's/8080/8081/' -i /etc/apache2/sites-available/001-cloud9.conf && \
phpmyadmin-ctl install | sed 's/.c9users.io/.c9users.io:8081/'
